### ISSUE TITLE
SIGMA - brak testu dynamicznego

### ISSUE THREAD

**Issue by BBedek** [brontesprocessing/vast.rehab#14]
soft vtrunk
jest tylko test stabilności, brakuje testu dynamicznego

**Comment by brontesprocessing** [comment]
Pracę jednonóż w teście dynamicznym wyprowadziłem do osobnego zgłoszenia. Test dynamiczny na Sigmie będzie dostępny w najbliższej upublicznionej po dniu dzisiejszym wersji.
