### ISSUE TITLE
kinect - test Fukudy

### ISSUE THREAD

**Issue by BBedek** [brontesprocessing/vast.rehab#8]
soft Vtrunk
kinect - test Fukudy
- Przy rotacji ciała w lewą stronę wynik wykazał moją rotację w prawą, dzieję się to również w starszej wersji kinecta
- nie liczy kroków

**Comment by brontesprocessing** [comment]
W temacie liczenia kroków - nie potrafię zreprodukować problemu. Warto może nadmienić, że kroki muszą być wyraźne - kolano podniesione przynajmniej na 45 - 90 stopni
